import  dbConnect  from "@/lib/mongo";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'
import { SessionProvider } from "next-auth/react";
import ClientSessionProvider from "@/ClientSessionProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const conn = await dbConnect();
 
  return (
    <ClientSessionProvider>
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
    </ClientSessionProvider>
  );
}
